// Lista de ícones/emoji para uso em mensagens do console.log
// Exemplo de uso: console.log(`${icons.success} Operação concluída!`)

export const icons = {
  info: 'ℹ️',
  success: '✅',
  error: '❌',
  warning: '⚠️',
  loading: '⏳',
  rocket: '🚀',
  star: '⭐',
  fire: '🔥',
  folder: '📁',
  file: '📄',
  db: '🗄️',
  check: '✔️',
  search: '🔍',
  up: '⬆️',
  down: '⬇️',
  right: '➡️',
  left: '⬅️',
  question: '❓',
  lock: '🔒',
  unlock: '🔓',
  warningAlt: '🚧',
  hourglass: '⌛',
  bug: '🐞',
  lightning: '⚡',
  robot: '🤖',
  magic: '✨',
  bell: '🔔',
  stop: '🛑',
  play: '▶️',
  pause: '⏸️',
  settings: '⚙️',
  globe: '🌐',
  cpu: '🧠',
  memory: '💾',
  network: '🌐',
  shield: '🛡️',
  pencil: '✏️',
  trash: '🗑️',
  plus: '➕',
  minus: '➖',
  folderOpen: '📂',
  calendar: '📅',
  mail: '✉️',
  link: '🔗',
  pin: '📌',
  eye: '👁️',
  mute: '🔇',
  speaker: '🔊',
  heart: '❤️',
  clap: '👏',
  party: '🥳',
  server: '🖥️',
};
