version: '3'

# 🏭 Taskfile Enterprise - Slice/ALIVE Providers Server
# Seguindo padrão: https://github.com/slice/ecosystem/docs/TASK_FILES.md
#
# Princípios:
# - Plug-and-Play Total: task install deve deixar tudo funcionando
# - Scripts organizados em /scripts (nunca comandos diretos aqui)
# - Validação Forte em cada etapa
# - Restauração Rápida do ecossistema
# - Incrementalismo: cada task valida antes de prosseguir

tasks:
  install:
    desc: "🚀 Instalação completa plug-and-play (CLP industrial)"
    cmds:
      - python3 scripts/install.py

  dev:
    desc: "🔧 Modo desenvolvimento com reload automático"
    cmds:
      - python3 scripts/dev.py

  start:
    desc: "▶️  Produção (servidor estável)"
    cmds:
      - python3 scripts/start.py

  test:
    desc: "✅ Executa todos os testes automatizados"
    cmds:
      - python3 scripts/test.py

  test-unit:
    desc: "🧪 Apenas testes unitários"
    cmds:
      - python3 scripts/test.py --unit

  test-integration:
    desc: "🔗 Apenas testes de integração"
    cmds:
      - python3 scripts/test.py --integration

  lint:
    desc: "🎨 Linting e formatação (black, isort, flake8, mypy)"
    cmds:
      - python3 scripts/lint.py

  validate:
    desc: "🔍 Validação completa (lint + test + health)"
    cmds:
      - python3 scripts/validate.py

  health:
    desc: "❤️  Health check do servidor"
    cmds:
      - python3 scripts/health.py

  models:
    desc: "📦 Gerenciamento de modelos HuggingFace"
    cmds:
      - python3 scripts/models.py {{.CLI_ARGS}}

  clean:
    desc: "🧹 Limpeza de arquivos temporários"
    cmds:
      - python3 scripts/clean.py

  reset:
    desc: "🔄 Restauração rápida do ambiente (< 30min)"
    cmds:
      - python3 scripts/reset.py

  logs:
    desc: "📋 Visualizar logs do servidor"
    cmds:
      - python3 scripts/logs.py

  shell:
    desc: "🐚 Shell interativo com ambiente carregado"
    cmds:
      - python3 scripts/shell.py

  deps:
    desc: "📊 Análise de dependências e licenças"
    cmds:
      - python3 scripts/deps.py

  benchmark:
    desc: "⚡ Benchmark de performance dos modelos"
    cmds:
      - python3 scripts/benchmark.py
