[tool.poetry]
name = "smol_dev"
version = "0.0.3"
description = "python module of smol developer"
authors = ["swyx <swyx@dontemail.me>"]
license = "MIT"
readme = "readme.md"
packages = [{ include = "smol_dev" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0.0"
openai = "^0.27.8"
openai-function-call = "^0.0.5"
tenacity = "^8.2.2"
agent-protocol = "^1.0.0"


[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["smol_dev"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.poetry.scripts]
src = "src.__main__:main"
api = "smol_dev.api:main"

[project]
name = "smol_dev"
version = "0.0.3"
description = "python module of smol developer"
authors = [
    {name = "Viviane Florido", email = "vivianeflowt@gmail.com"},
    {name = "swyx", email = "swyx@dontemail.me"},
]
dependencies = [
    "openai>=0.27.10",
    "openai-function-call>=0.1.2",
    "tenacity>=9.1.2",
    "agent-protocol>=1.0.2",
    "python-dotenv>=1.1.0",
]
requires-python = "<4.0.0,>=3.10"
readme = "readme.md"
license = {text = "MIT"}

[project.urls]
"Homepage" = "https://github.com/smol-ai/developer"
"Bug Tracker" = "https://github.com/smol-ai/developer/issues"

[project.scripts]
src = "src.__main__:main"
api = "smol_dev.api:main"
