[project]
name = "admin"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Viviane Florido", email = "vivianeflowt@gmail.com"},
]
dependencies = ["fastapi>=0.115.12", "uvicorn>=0.34.2"]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
